### ISSUE TITLE
Security vulnerability comment

### ISSUE THREAD

**Issue by adubey14** [scope-lab-vu/fire-department-analytics-dashboard#2]
Please see the warning from github on the repository page

**Comment by gap101** [comment]
I don't see a warning; I'm not sure what it is you're referring to.

**Comment by gap101** [comment]
@ayanmukhopadhyay you should be able to see the vulnerability comment now at the top of the main repo page. It says that we should use a newer version of the requests library; the code currently uses 2.18, but we should use =>2.20.0. Is there a specific need for 2.18?

**Comment by adubey14** [comment]
Has this issue been resolved

**Comment by ayanmukhopadhyay** [comment]
I haven't worked on this. Let me check and get back.

**Comment by adubey14** [comment]
Thanks. One of the requirements has to be changed. Can you also ensure code is up to date in github

Sent from my iPhone

On Mar 15, 2019, at 5:01 PM, Ayan Mukhopadhyay <notifications@github.com<mailto:notifications@github.com>> wrote:


I haven't worked on this. Let me check and get back.

**Comment by gap101** [comment]
The library has been updated to its newest version, and the vulnerability is resolved.
